# Generated by Django 3.0.2 on 2020-02-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('presenter', models.CharField(max_length=20)),
                ('descripton', models.CharField(max_length=250)),
                ('presentaion_link', models.URLField(max_length=300)),
                ('author_link', models.URLField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentations',
                'ordering': ('-created',),
            },
        ),
    ]
